### ISSUE TITLE
Abstract the Observable type

### ISSUE THREAD

**Issue by dwhitney** [Callidon/sparql-engine#15]
**Is your feature request related to a problem? Please describe.**

I brought this up in #3 and I'd like to revisit it before I attempt an implementation. 

There is significant overhead in using `Observable`, and I'd like to abstract the type away while still providing a concrete implementation with it.

For some context - I've written my own triple store because those available were either too slow or too memory hungry. The triple store I've written can often return results in the 10s to 100s of microseconds, but streaming the results through `rxjs` turns those 10s to 100s of microseconds into 10s to 100s of milliseconds. The JS runtime will often optimize this if a graph is reused, but the results are still not great. And for my use case, the runtime doesn't really get a chance to do much optimization since I will often run a query against a graph just once.

From my perspective, if the query is streaming across the network, `Observable` is great, because it'll keep memory consumption low, and it's what you'd want, but often in my case, I already have the data in an `Array`, and pushing each triple through `Observable` adds a ton of overhead for really no gain. If I could *choose* my "stream" type, then I could use `Observable` when it makes sense, or just get a "pure" piece of data back when that makes sense. 

The example of this I've used most is from a Scala library called [fs2](https://fs2.io/). In essence you have a `Stream` type with two type arguments - the first represents the stream's container, which could be something like `Observable` or `Identity`, and the second represents the type contained, which would be `Algebra.TripleObject` in the case of the `find` function. You can do all sorts of nice `map`, `fold`, `reduce` things etc on it, and once you're ready for it to run you call `run` (or something similar), and out pops your `Observable` or `Identity` (`Identity` will just give you a pure data structure if that's what you want). More *streaming* libraries can be supported by simply implementing a few interfaces. 

I wanted to get your feedback before attempting anything.

Thanks!

**Comment by JuniperChicago** [comment]
@dwhitney, et all. Just to chime in, because I believe it is possible to run a personal sized graph in the browser and nodejs, so your point is of interest to me too. I have some experience with a library called [cycle.js](https://github.com/cyclejs/cyclejs), which initially used RxJS, then was abstracted with an adapter system to accept additional stream libraries like [most.js](https://github.com/cujojs/most). The design of cycle.js might be of interest here, and the performance of most.js is impressive enough to stick with the benefits of these reactive streams provide... imho.

**Comment by Callidon** [comment]
I've finally had some time to thinks about this (sorry for the delay).
To give some insight, this project was initially a complete client for one approach of my lab team, [SaGe](http://sage.univ-nantes.fr/). Later on, we decided that most of the SPARQL engine components could be abstracted into a general framework, similar to [Apache Jena](https://jena.apache.org/), which leads us to this library.
So, yes, `sparql-engine` was initially intended for querying RDF graphs hosted on remote sites (like SPARQL endpoints or SaGe servers). However, it clearly go over this context now.

In `sparql-engine`, I've implemented an **iterator based pipeline** for query execution. This is the state of the art technique in database systems for implementing a query engine (see [Database Systems: The complete book](https://theswissbay.ch/pdf/Gentoomen%20Library/Databases/Molina%2CUllman%20-%20Database%20Systems%20The%20Complete%20Book.pdf), Chapter 15, for more details). This approach has two big advantages: no intermediate results are materialized and it enforces a modular architecture by breaking everything into independent operators. To build such pipeline, we need a library that allows stream:/iterator based transformations.

Typically, the stream abstraction should not be a built-in feature of this framework, because there is nothing SPARQL related in that. Hence, we should rely on an external library for that. That's the idea behind using RxJs (and asynciterator.js before it): have a very general stream/iterator framework that allows all kind of transformations we need (`filter`, `map`, `mergeMap`, etc). Of course, such framework needs top-notch performance, because the query execution pipeline can quickly become a bottleneck during query execution.

About `fs2`, I've got the genral idea but I've strugguling to understand how it sould look like. @dwhitney do you have an example close to what we need?

**Comment by dwhitney** [comment]
First, I really like this library. It's one of the better libraries in the
world, and I feel very fortunate that I get to use it! Second, yes I like
the pipeline approach. It's really nice! My suggestion was more about
abstracting out RxJs as the underlying handler for the pipeline. There are
situations where it's a performance bottleneck, and it may be nice to swap
it out with something else. For example, I often have a pure, in-memory
data structure that processes BGPs in 10s to 100s of microseconds, but when
it's all wrapped up RxJs, those microseconds become milliseconds.

If you take a look at fs2's `Stream` (
https://oss.sonatype.org/service/local/repositories/releases/archive/co/fs2/fs2-core_2.12/1.0.1/fs2-core_2.12-1.0.1-javadoc.jar/!/fs2/index.html#Stream[+F[_],+O]extendsAnyVal).
You can see that there are two type parameters, `F[_]` and `O`. `O` is
fairly straight forward and represents the type of thing you are streaming
(`String`, `Int`, `User`, etc.), but `F[_]`, represents the underlying
`Stream` implementation. So in Scala this could be anything from `Future`,
`Task`, `Identity`, `Effect`, `Free`, etc. etc. But the basic point is,
with fs2 if you'd like to make something be your `F[_]`, you just have to
implement a few type classes and it just works.

This is what I'd like to see in `sparql-engine`. So when you say,
"Typically, the stream abstraction should not be a built-in feature of this
framework, because there is nothing SPARQL related in that.", we are in
agreement! But I'm saying let's take it a step further. Rather than
supplying a single concrete implementation for the stream/iterator in RxJs,
why not describe what that iterator should look like with type classes
(probably derived from here: https://gcanti.github.io/fp-ts/) and let
anyone supply an implementation. There could be a standard RxJs
implementation, and implementations for Node.js Stream, EventEmittters,
Futures, Promises, something from most.js, as @JuniperChicago suggested,
etc.

I realize this is no small task, and I currently don't have bandwidth to
take it on, but perhaps some time will open up and I could take a stab at it

D

**Comment by Callidon** [comment]
Hum, interesting. So, if i understand correctly, I should look something like that (with heavy simplication)

```typescript
interface Stream<T, F> {
 static from(input: ObservableInput<T>): F;
 static map(input: F, cb: (x: T) => T): F;
 static filter(input: F, cb: (x: T) => boolean): F;
 static mergeMap(input: F, cb: (x:T) => F): F;
 // etc ....
}

class RxjsStream<T> implements Stream<T, Observable<T>> {
 static from(input: ObservableInput<T>) {
    return rxjs.from(input)
 }
 static map(input: F, cb: (x: T) => T) {
    return input.pipe(map(cb))
 }
}
```

**Comment by dwhitney** [comment]
Yeah something like that. There are some interfaces out there already that
would be a good fit rather than defining your own. I've used Funfix:
https://github.com/funfix/funfix and it's written by a guy who has created
some incredibly good and performant Scala libraries. This one looks decent:
https://github.com/rzeigler/waveguide and states some advantages over
Funfix, but I don't know anything about the author.

D

**Comment by Callidon** [comment]
I think I'm going to allocate some time to this issue, because it is a real improvement for the current framework.

**Comment by dwhitney** [comment]
In case you're interested:

It looks like @mpilquist gave a talk on fs2 today at NEScala:
https://speakerdeck.com/mpilquist/fs3-evolving-a-streaming-platform It's
just slides, but and/or @pchiusano have both probably given talks on fs2.
They are both great speakers and engineers. and completely OT, @pchiusano's
Unison project is really interesting.

**Comment by JuniperChicago** [comment]
@Callidon I agree with @dwhitney that your efforts with `sparql-engine`, while clearly meant to be a lightweight client to a larger system, is the most complete and thoughtful implementation of SPARQL 1.1 currently found in open-source javascript (IMHO). For me, after working around other implementations for several years, I find `sparql-engine` to be a natural starting point for more complete SPARQL 1.1 capabilities in javascript. I am sitting on a fork right now that completes the graph management operations, but am trying to make your current implementation friendlier to this kind of extensibility... which I have pretty much finished and will post on my fork and get input. But again, nice work Thomas and all who have contributed!

**Comment by Callidon** [comment]
@JuniperChicago Thank you. For your information, I have a team of Master students working on an implementation of all SPARQL property paths (as a school project). They have started the benchmark phase last week, and I think they should be able to merge their work no later than next month.

**Comment by Callidon** [comment]
So, after a complicated night, I came up with a first working version of an abstracted pipeline. I had to move away from the initial proposal, but I managed to get a good draft.
I've pushed everything on the branch https://github.com/Callidon/sparql-engine/tree/external-pipeline

However, it's a major breaking change from the previous archtecutre, as it impacts around 80% of the projet's source files. So @dwhitney @JuniperChicago check out your forks, they are likely to break if we merge this into the master branch.

**Comment by dwhitney** [comment]
Awesome! I've got a really busy day, but I'll check it out tonight

D

**Comment by dwhitney** [comment]
Hey I just had a chance to look at this. I didn't know about `ObservableInput`. It looks like it will resolve the issue's I outline, which is great!  That said an orthogonal criticism I'd have of this library is that there are a few too many dependencies, which makes for large bundles. I know about rollup and tree-shaking, etc, but I'd rather avoid them since I'm skeptical of how well they work. With `ObservableInput` there is still a dependency on rxjs, which is a bit frustrating if the user isn't using it anywhere else. 

I suggested `fp-ts`. There are some functional abstractions there that I feel could provide all of the abstractions needed for this library (maybe - but if not I proposed a couple of others), and the dependency would be quite small in comparison to rxjs. From there you could conceptually provide a `sparql-engine-rxjs` or `sparql-engine-most` which were concrete implementations of the abstractions provided by `fp-ts`.

From what I've seen it feels like the [IO monad](https://gcanti.github.io/fp-ts/modules/IO.ts.html) could be used for everything you need, and there are already a couple of libraries with bindings for most and rxjs, which may be all that's needed for your concrete implementations.

That said, I realize the functional programming stuff is a bit of a mental leap if one hasn't used it much, and the only upside from what you've provided would be increased flexibility and smaller bundles. It may not be worth the trouble.

**Comment by Callidon** [comment]
About `ObservableInput`, it's actually a type alias defined by `rxjs` from native javascript types. So we could embed it directly into `sparql-engine`.

Next, I have some doubts about introducing functionnal programming here, same as you highlighted. For me, bundle size here is not the main focus, as this library can be used both for Node.js and browsers.

Finally, I prefer to leave `rxjs` as the default implementation. It will be fine for most users, and if they need more, we could still provide alternative pipeline implementations as external packages. For example, a V8-based pipeline, built in C++, could be a nifty improvement for Node.js users :)

**Comment by Callidon** [comment]
Anyways, should we merge the [`external-pipeline`](https://github.com/Callidon/sparql-engine/tree/external-pipeline) branch into `master`? Overall, I think it's a net improvement for the project, and it will give us a strong base if we want to implement something crazier.

Additionally, as this a breaking change from the previous version, I would like to merge it as quick as possible, since my students working on the property paths evaluation will have to take it into account asap.

**Comment by dwhitney** [comment]
yeah I'm good with that. Maybe give it a full version bump?

**Comment by JuniperChicago** [comment]
@Callidon I went to built a pipeline for most.js, and got hung up with the `PipelineEngine` close coupling with `PipelineState` and the specific implementation of `Observable` as found in `rxjs`. I think one more level of coupling needs to be removed alowing the developer to define the interface of the `Observable` class used without extending the `Observable` from a specific chosen library. `PipelineEngine` pretty much does this already, so it seems like methods within should return new instances of `PipelineEngine`, or something like that.

**Comment by Callidon** [comment]
@JuniperChicago I'm not releasing the merge yet, because I need to write down a couple of tests for the brand new `RxjsPipeline`. This way, we will have a solid base of tests fixtures for testing all future `PipelineEngine` implementations.

The close coupling between `PipelineEngine` and `PipelineStage` is mandatory for me, I don't see how to deal without it. The idea is indeed to let the developer define its own `Observable` as an implementation of the `PipelineStage` interface.

Anyways, I've planned to add a `VectorPipeline` to the pipeline, which will perform all pipeline operations using in-memory arrays (the technique is called vectorization in database systems). Maybe I will see more clearly your problem by doing so.

**Comment by dwhitney** [comment]
I tried this out. There are bugs when I run the tests

**Comment by dwhitney** [comment]
I was just looking through the issues. I think this can be closed now!
