### ISSUE TITLE
The N3 example is not working...

### ISSUE THREAD

**Issue by jbouecke** [Callidon/sparql-engine#42]
**Describe the bug**
The N3.js implementation example seems to be outdated. It's not working for several reasons

e.g. Store is a constructor and needs to be called with 'new', the N3 store fully relies on rdf.js spec terms (not on strings), ...

**Expected behavior**

I attached a working example.

[sparql-engine-n3-example.txt](https://github.com/Callidon/sparql-engine/files/4262258/sparql-engine-n3-example.txt)

**Comment by Callidon** [comment]
Hi

The N3.js example was developed with a specific version of N3.js (0.11.3). You can use the `package.json` file in the `examples` directory to install it. Indeed, since then, N3.js has changed drastically its API. However, we will not update the example with the last version of N3.js, as it is just here to demonstrate the usage of the framework.

**Comment by Callidon** [comment]
I'm closing this issue due to the lack of interactions. Feel free to re-open it if you think it's needed.
